### PR TITLE
make it compatible with new hashing

### PR DESCRIPTION
**Pull request by narimiran**
This is now the corrected version: the new hashing algo was slightly tweaked and it won't be part of Nim v1.0.2, so the modifications are needed only for devel (v1.0.99) and for future minor versions (v1.1, etc.).

### CODE REVIEW

**Comment by def-** [comment]
lgtm, you could also sort the results and then compare so that the comparison stays the same.

I'm not sure I understand why the order changes btw, could you explain?

**Comment by narimiran** [comment]
> I'm not sure I understand why the order changes btw, could you explain?

Before `hash(123) == 123` (for any `int` its hash was that int), plain and simple. The problem was when collisions start to occur in `HashSet` or `HashTable`, because every hash is bitmasked with the container length, so different (consecutive) integers might want to go into the same bucket, over and over and over again, which caused huge slowdowns.

The fix proposed in https://github.com/nim-lang/Nim/pull/12407 makes `hash(123) == 123 * 11`, which hugely helps with avoiding collisions, making everything three orders of a magnitude faster! The consequence of this different hashing algorithm is that keys are now not sorted the same as they were before.

> you could also sort the results

This is probably a better solution, as one should not depend on some internal order of things.

**Comment by def-** [comment]
Aaah, finally I understand, it's because of the "let d = {1: 4, 2: 5, 3: 6}.toTable". Better fix would be to make that have deterministic order. Do you want to do so or should I? I think `values(d)` could just be [4, 5, 6] instead.

**Comment by narimiran** [comment]
> Do you want to do so or should I?

I think we will save at least one iteration if you do it :)

**Comment by def-** [comment]
Done.

**Pull request closed without merging**
